### PR TITLE
Fixed firefox 33+ priveleged scope issue by copying the scope to the …

### PR DESCRIPTION
**Pull request by fat-troll**
…local one

It's also fixing https://github.com/SeleniumBuilder/se-builder/issues/185

### CODE REVIEW

**Comment by fat-troll** [comment]
Don't know if it's possible to test something here.

**Comment by Zarkonnen** [comment]
Sorry, can you explain a little bit what this does?

**Comment by fat-troll** [comment]
So, basically you can see such kind of warning in console while performing actions from #185 : 

```Security wrapper denied access to property length on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported.```
This feature was first introduced in firefox 33 (turned off by default) and then turned on with 34 or 35 (pretty hard to track, as it seems like they did it in different version depending on OSes). 

Some info on feature: http://codeverge.com/mozilla.dev.b2g/notice-do-not-add-new-instances-of-exposedpro/1992161, and a quick quote from it: `As part of our effort to move to more robust bindings, we've deprecated Chrome Object Wrappers (COWs) and the __exposedProps__ tables that support them.`

So, what is it doing: it takes the DOM objects (`wrapReflection:true`) and safely copying them into the needed scope `sandbox`: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_Bindings/Components.utils.cloneInto . Since ff33-35 it's the safest way to get access to some of DOM objects and it's properties.

**Comment by Zarkonnen** [comment]
Thanks for the details. Merging this now and will be releasing v2.3.5 in a bit. :)

**Pull request merged**
